### ISSUE TITLE
Add-on should know what type of tile you clicked on

### ISSUE THREAD

**Issue by Verdi** [bwinton/newtabsnippet#3]
Maybe it already does this but it should be able to tell if you clicked on a regular history tile, a directory tile or a sponsored tile.

**Comment by bwinton** [comment]
So, history tiles have `.newtab-site[type="history"]`,
and sponsored tiles have `.newtab-site[type="sponsored"]`,
does that mean that directory tiles are everything else?

**Comment by bwinton** [comment]
(I notice some tiles have `.newtab-site[type="affiliate"]`.  Maybe I should just always log the type, and we can figure it out on the back-end…)

**Comment by bwinton** [comment]
Fixed by 2ea88cf948358f9106adcea1acf21f577b701878

**Comment by bwinton** [comment]
(Uh, that's supposed to be 2ea88cf948358f9106adcea1acf21f577b701878)
