### ISSUE TITLE
about:newtab should not be the home page for bucket 0

### ISSUE THREAD

**Issue by Verdi** [bwinton/newtabsnippet#5]
When I'm in bucket 0 shouldn't it be essentially no different than not having the add-on?

**Comment by bwinton** [comment]
I don't think so, since we want to test how the snippet affects clicks, so we want to send people to the same page in both scenarios…  (Do you agree?  Should we ask other people, like, say, Bill and/or Gemma, for their thoughts?)

**Comment by Verdi** [comment]
You're right. We have Firefox without the add-on as the baseline.
